# Generated by Django 5.1.3 on 2025-11-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_daily_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_character',
            field=models.CharField(default='default', help_text='Selected character skin (default, zoro, etc.)', max_length=50),
        ),
    ]
