# Generated by Django 5.2.6 on 2025-11-23 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_selected_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_slot',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('helmet', 'Helmet'), ('chest', 'Chest'), ('legs', 'Legs'), ('feet', 'Feet'), ('accessory', 'Accessory')], default='accessory', help_text='Visual equipment slot for character rendering', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='gold_cost',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sprite_path',
            field=models.CharField(blank=True, help_text='Relative path to sprite image (e.g., equipment/helmets/iron-helmet.png)', max_length=255),
        ),
    ]
