# Generated by Django 5.2.6 on 2025-11-24 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_equipment_equipment_slot_equipment_gold_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('base_hp', models.IntegerField(default=50)),
                ('base_damage', models.IntegerField(default=5)),
                ('sprite_path', models.CharField(blank=True, help_text='Path to enemy sprite', max_length=255)),
                ('xp_reward', models.IntegerField(default=20)),
                ('gold_reward', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='TowerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.IntegerField(default=1)),
                ('highest_floor', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tower_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
