# Generated by Django 5.1.3 on 2025-11-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_equipment_equipment_slot_equipment_gold_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_theme',
            field=models.CharField(default='Default Theme', help_text='Selected theme/background (e.g., Default Theme, Forest Green, etc.)', max_length=200),
        ),
    ]
