# Generated by Django 5.1.3 on 2025-11-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_0006_customuser_selected_theme_0006_enemy_towerprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='character_specific',
            field=models.CharField(blank=True, help_text="If set, this armor/relic is only for this character (e.g., 'zoro', 'default')", max_length=50),
        ),
    ]
