# Generated by Django 5.1.3 on 2025-11-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_selected_appearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_slot',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('helmet', 'Helmet'), ('chest', 'Chest'), ('armor', 'Armor'), ('legs', 'Legs'), ('feet', 'Feet'), ('accessory', 'Accessory')], default='accessory', help_text='Visual equipment slot for character rendering', max_length=20),
        ),
    ]
