# Generated by Django 5.1.3 on 2025-11-29 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_selected_appearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='xp_reward',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
