# Generated by Django 5.2.6 on 2025-12-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_equipment_equipment_slot'),
        ('api', '0009_alter_habit_xp_reward'),
    ]

    operations = [
    ]
