# Generated by Django 5.1.3 on 2025-12-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20251201_2351'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'name'), name='unique_active_habit_name_per_user'),
        ),
    ]
